name: expense_tracker
description: "Minimal expense tracker."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0-287.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  json_annotation: 
  hive_ce:
  hive_ce_flutter:

  stacked_shared: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 
  json_serializable: 
  stacked_generator:
  hive_ce_generator:
flutter:
  uses-material-design: true